# Generated by Django 2.1.1 on 2018-10-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('receiver', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date send')),
                ('chronological_order', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('text', models.CharField(max_length=50000)),
                ('client_code', models.CharField(blank=True, max_length=200)),
                ('study', models.CharField(blank=True, max_length=200)),
                ('data_set', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explomail.Client')),
            ],
        ),
    ]
